# Generated by Django 5.1.1 on 2024-09-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_caisse', '0001_initial'),
        ('app_paiestudent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortiecaisse',
            name='paiEtudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_paiestudent.paiement'),
        ),
        migrations.AddField(
            model_name='operationcaisse',
            name='sortie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_caisse.sortiecaisse'),
        ),
    ]
