# Generated by Django 5.1.1 on 2024-09-26 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_Inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_paiement', models.CharField(max_length=100)),
                ('info_etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Inscription.inscription')),
            ],
        ),
    ]
