# Generated by Django 5.1.1 on 2024-09-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('etat_civil', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
            ],
        ),
    ]
