# Generated by Django 4.2.15 on 2024-09-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('postnom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('genre', models.CharField(choices=[('homme', 'femme')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cycle.cycle')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cycle.filiere')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cycle.promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
